---
# tasks file for ansible-role-nn-base

- name: Install packages
  package:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
    - open-iscsi
    - nfs-common